### ISSUE TITLE
Should the unwrapping versions of queries be separate functions?

### ISSUE THREAD

**Issue by sluukkonen** [sluukkonen/possu#8]
If so, how should they be named?

`queryColumn`, `queryOneColumn`, `queryMaybeOneColumn` ? `queryColumn`, `queryColumnOne`, `queryColumnMaybeOne` ?
`queryCol`, `queryOneCol`, `queryMaybeOne` ? `queryCol`, `queryColOne`, `queryColMaybeOne` ?
`queryOnly`, `queryOneOnly`, `queryMaybeOneOnly` ? `queryOnly`, `queryOnlyOne`, `queryOneOnlyMaybe` ?

TBD.

**Comment by googol** [comment]
Yeah one function returning two different kinds of results based on a sql string sounds dangerous, so probably best to separate them. Unless you want to write a SQL parser with TS types :D

**Comment by sluukkonen** [comment]
You’ll have to write correct TS return types by hand in any case, so I don’t think it’s necessarily a big deal. 

But really, I’m not sure if doubling the API surface is worth the trouble, since in my experience, one very rarely wants to select single-property objects from the database. Those kinds of queries are almost always succeeded by some bit of code that extracts the only property out of the object.
